baseURL = "https://mytaditya.vercel.app/"
locale = "en-us"
title = "Mastered YT Aditya's Official Website"
theme = "mana"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  description = "Get the latest official updates from Mastered YT Aditya at here!"
  favicon = "/favicon/favicon.ico"
  heroTitleLine1 = "Mastered YT Aditya's"
  heroTitleLine2 = "Official Website"

[params.avatar]
  [params.avatar.home]
    assetPath = "images/transparent-logo.png"
  [params.avatar.about]
    assetPath = "images/logo.png"
	
[params.social]
  github = "https://github.com/MYTAditya"
  twitter = "MYTAditya"

[params.codeHighlight]
  darkTheme = "aura-theme-dark"
  lightTheme = "catppuccin-frappe"
  
[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menus.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 20

[[menus.main]]
  name = 'Tags'
  pageRef = '/tags'
  weight = 30

[[menus.main]]
  name = 'About'
  url = '/about/'
  weight = 40
  
[pagination]
  pageSize = 10
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
	  
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false

  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    style = "aura-theme-dark"
